language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
- pip install coveralls
- pip install pytest-cov
script:
- python -m pytest --cov=tutorial
after_success:
- coveralls
env:
  global:
  - secure: pQz5fqYLfIU5Ly0JGoXb87df/XM7U4yY2914ht0Cnsn9rVXnlZwRHv/u6t/q51p4BCSyz7E4N5jAXauLkwRmN5q+DyVxjNigoDsj1qpiGGnJHleUP61Hl5Q6opI7eUZQ+NwxSGFEY6xyj8oXOCxgL2JaaRIWOJmCopsarx8nxbXziJ/HDBIPn6k+eN5SmPv6ooBUk/7CKJPLr+F2hBHtFCYUJq5SXVJ6JeMfcckdDjjlk6J7APXHI7mvfs+vTSeS4wYK9j1+tXyvgjPzz+So1uls0m2R+nxbsEgzADZnurLSx7oQI1ZakKY3KZUV7G7JGtCkQCDrB36rge93gRHDtWwsOMTqUvCxehIUa8doKbk2STL5rMmPRpRHZUXx1DEK0q7kzvaqx4G4JizDak2TIsMCzIethtGLAw3DmTS7zlPYDN/xNOeRnYUi9toz5XWIgmeQYXPnH5yyrgZnKTZTqbyH2IUliLA6AL6dYQi8Ttq8Ow8N9N+TS81pfhmoFqcfRlCQ50vwPR+/WZhKFDEsEDnl42TBeoPW4Oc4arsz0ZkO2oQV6/3bLvkEF7CiVSnK+o6FelTeSoQySEg09NWfd9ZgvZ/D9koXWqsme76Uk0Uf1TR/iHO5TqbokQt/ANmjrhtCO36BZkIITHU7pbF747IZ9fgbebbDxx+OedL9hk8=
  - secure: LEv1/prflLuu2FS1yig94yB3bIe3gBXKdQAxT0OAEcIZwTxZ9RG+7O0QS+bHNOAdL2vWO7G8JTazSk618pXMJa0p70FAPuzn29nsE+d6QFoQTKVajfUTjQYKGk0rN627ST8aQ0CMD2BDpleS9BxP9VJNVv3Z03tNvqcRhygeJKqvzC2C2hqNIGUEOt80/OJ/f7v9KlrdSEmj5jlRRinokAINgdp4w4L/0fx0K8SItyQA9SY230jliQxhnyIIt0xNW4SA49G30F9BK93SDI97qah4zexvRrPoqQCTRR6X4/gKvk8Q95KCgNR99Ythu4PNrr6zTcDBg4tlFq+sqxbWTSRoGqRFzwLdAqp2fuXModEjwyFF0+I9GK0/aVk/S9Y4Y24jUb6Xm93ROMzuwgsV53yjvJoHczv4PsSBxTNR3bPjQ8zb9T5cETeeluTm5jBlqYcJUJQas+dPwe3nt5NMPyZ8Ff/slVhvNnDNQ3KYO8uEvD5MkUPupfy79jw4RyFWW4jRIv/PWQLr3Pksj0HY0Dlmz2M0A+hyOQu516r1lkrs4MbC2GjfVJ6vLApahQm8qjQYe955hmJ5ennl/maBMGV+hN8PONPFw7gaXhzWLPqd8jBIjdZus9iUtmq+qf75juPFZMDCtDoQO0fw1UkMsKsCWBG0zvwbiRkYdr0L0fg=

deploy:
  provider: heroku
  api_key:
    secure: Qkp0JcdyNbcgVVrDywSw0X4oR8YhXrq+ii7c2Xw4XfeiiPexU8WoRTx/Sk8PLqInWAQU0QP3SQNxE56o/birl25FAMblGguNcNVJJK7PFdrBjrvIwrfihunTbZmKriXGkOUcCmXaObvt6jz5aIcNu66//TYiZQL7rKOB5JhIaJvy18Wjpj7REt3ifIcwcRH4+QGouxfVDMThGjnl56Po71kJsPf+lhgsGVxEH8/S8cki9jSz5NcDblE4tFBPZ9+BQCzltVRmVDasQr/yytQhwJYTG1ATyIewWspokLCPeZCoGMKJIRIiGFmHo+wjIIuHdqdPCrmPCbCfRLVpQpwksqXVIu5fyx55d0zwTMkIrPDAzV9UBWg/bllxkTGYWpQCu+Eq9GyvvE1aJ05aCSu43cAWs9rymXnws2Q73fLXZhyXOVLIePpACjRcTtKAo8U/nrgGhZPxP6hZG62QX5iRH7JMFxgpM6qXQZ/ZIHiM61o/b83/A1JfxMVp7Yr9KRqrppozBUKtLdHEtKY9qWCZ42Qqth6Ji05/9ubODUdM51DZPEEHvjYXM1LA8JnX/a2xAZcm8GBqv7Lk3pEJaVTFgDKwa5vFkLREtfv1F6lpV6vtFpOeL6I7B4i/nsZXXZOg775SAKduu+YRyrsIUSqusBTFN0NaSeI/MQD9fcvu17U=
  on: master
  run: "heroku run python manage.py migrate"

branches:
  only:
  - master
  - stable
